-- Generated by athanor transmute ({{ label }}). Edits are overwritten.
hl.config({
    general = {
        col = {
            active_border = "rgb({{ active.hex }})",
            inactive_border = "rgb({{ border.hex }})",
        },
    },
    misc = {
        background_color = "rgb({{ bg.hex }})",
    },
})
