-- Generated by athanor transmute ({{ label }}). Edits are overwritten.
return {
    "{{ wall_1 }}",
    "{{ wall_2 }}",
    "{{ wall_3 }}",
    "{{ wall_4 }}",
    "{{ wall_5 }}",
    "{{ wall_6 }}",
    "{{ wall_7 }}",
}
