-- Uses the terminal's 16 colors, so it follows the scheme. Badges are reversed
-- accents: slot 0 is the ink in the light schemes, so only the terminal's own
-- background reads on an accent in all four.
vim.cmd.highlight("clear")
vim.g.colors_name = "athanor"
vim.o.termguicolors = false

local red, green, yellow, blue, magenta, cyan = 1, 2, 3, 4, 5, 6
local gray, bright_red, bright_green, bright_yellow = 8, 9, 10, 11

local groups = {
    Normal = {},
    NormalFloat = {},
    NormalNC = {},
    Comment = { ctermfg = gray },
    Constant = { ctermfg = magenta },
    String = { ctermfg = green },
    Character = { ctermfg = green },
    Number = { ctermfg = magenta },
    Boolean = { ctermfg = magenta },
    Float = { ctermfg = magenta },
    Identifier = {},
    Function = { ctermfg = bright_yellow },
    Statement = { ctermfg = red },
    Keyword = { ctermfg = red },
    Conditional = { ctermfg = red },
    Repeat = { ctermfg = red },
    Exception = { ctermfg = red },
    Label = { ctermfg = yellow },
    Operator = { ctermfg = gray },
    PreProc = { ctermfg = red },
    Include = { ctermfg = red },
    Define = { ctermfg = red },
    Macro = { ctermfg = yellow },
    Type = { ctermfg = cyan },
    StorageClass = { ctermfg = red },
    Structure = { ctermfg = cyan },
    Typedef = { ctermfg = cyan },
    Special = { ctermfg = yellow },
    SpecialChar = { ctermfg = cyan },
    Tag = { ctermfg = red },
    Delimiter = { ctermfg = gray },
    SpecialComment = { ctermfg = gray, cterm = { bold = true } },
    Debug = { ctermfg = yellow },
    Underlined = { ctermfg = blue, cterm = { underline = true } },
    Error = { ctermfg = red, cterm = { bold = true } },
    Todo = { ctermfg = yellow, cterm = { bold = true } },
    Title = { ctermfg = yellow, cterm = { bold = true } },
    Directory = { ctermfg = blue },

    LineNr = { ctermfg = gray },
    CursorLineNr = { ctermfg = yellow },
    CursorLine = {},
    CursorColumn = { cterm = { reverse = true } },
    ColorColumn = { cterm = { reverse = true } },
    SignColumn = {},
    FoldColumn = { ctermfg = gray },
    Folded = { ctermfg = gray },
    Visual = { cterm = { reverse = true } },
    Search = { ctermfg = yellow, cterm = { reverse = true } },
    IncSearch = { ctermfg = bright_yellow, cterm = { reverse = true } },
    CurSearch = { ctermfg = bright_yellow, cterm = { reverse = true } },
    Substitute = { ctermfg = red, cterm = { reverse = true } },
    MatchParen = { ctermfg = yellow, cterm = { underline = true } },
    NonText = { ctermfg = gray },
    Whitespace = { ctermfg = gray },
    SpecialKey = { ctermfg = gray },
    EndOfBuffer = { ctermfg = gray },
    Conceal = { ctermfg = gray },
    WinSeparator = { ctermfg = gray },
    VertSplit = { ctermfg = gray },
    FloatBorder = { ctermfg = gray },
    FloatTitle = { ctermfg = yellow },
    StatusLine = {},
    StatusLineNC = { ctermfg = gray },
    TabLine = { ctermfg = gray },
    TabLineFill = {},
    TabLineSel = { ctermfg = yellow, cterm = { reverse = true } },
    WinBar = {},
    WinBarNC = { ctermfg = gray },
    Pmenu = {},
    PmenuSel = { cterm = { reverse = true } },
    PmenuSbar = {},
    PmenuThumb = { cterm = { reverse = true } },
    WildMenu = { cterm = { reverse = true } },
    QuickFixLine = { ctermfg = yellow },
    ModeMsg = { ctermfg = yellow },
    MoreMsg = { ctermfg = green },
    Question = { ctermfg = green },
    ErrorMsg = { ctermfg = red },
    WarningMsg = { ctermfg = yellow },

    DiffAdd = { ctermfg = green },
    DiffChange = { ctermfg = yellow },
    DiffDelete = { ctermfg = red },
    DiffText = { ctermfg = yellow, cterm = { bold = true, underline = true } },
    Added = { ctermfg = green },
    Changed = { ctermfg = yellow },
    Removed = { ctermfg = red },

    SpellBad = { cterm = { undercurl = true } },
    SpellCap = { cterm = { undercurl = true } },
    SpellRare = { cterm = { undercurl = true } },
    SpellLocal = { cterm = { undercurl = true } },

    DiagnosticError = { ctermfg = red },
    DiagnosticWarn = { ctermfg = yellow },
    DiagnosticInfo = { ctermfg = blue },
    DiagnosticHint = { ctermfg = gray },
    DiagnosticOk = { ctermfg = green },
    DiagnosticUnderlineError = { cterm = { undercurl = true } },
    DiagnosticUnderlineWarn = { cterm = { undercurl = true } },
    DiagnosticUnderlineInfo = { cterm = { underline = true } },
    DiagnosticUnderlineHint = { cterm = { underline = true } },
    DiagnosticUnnecessary = { ctermfg = gray },
    DiagnosticDeprecated = { cterm = { strikethrough = true } },
    LspInlayHint = { ctermfg = gray },
    LspReferenceText = { cterm = { underline = true } },
    LspReferenceRead = { cterm = { underline = true } },
    LspReferenceWrite = { cterm = { underline = true } },

    ["@variable"] = {},
    ["@variable.builtin"] = { ctermfg = yellow },
    ["@variable.parameter"] = {},
    ["@variable.member"] = {},
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Constant" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.regexp"] = { link = "SpecialChar" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Function" },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@constructor"] = { link = "Type" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.operator"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Special" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@module"] = { ctermfg = blue },
    ["@attribute"] = { ctermfg = blue },
    ["@label"] = { link = "Label" },
    ["@property"] = {},
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { ctermfg = blue },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@comment"] = { link = "Comment" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.error"] = { ctermfg = red, cterm = { bold = true } },
    ["@comment.warning"] = { ctermfg = yellow, cterm = { bold = true } },
    ["@comment.note"] = { ctermfg = blue, cterm = { bold = true } },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.strong"] = { cterm = { bold = true } },
    ["@markup.italic"] = { cterm = { italic = true } },
    ["@markup.strikethrough"] = { cterm = { strikethrough = true } },
    ["@markup.link"] = { ctermfg = blue },
    ["@markup.link.url"] = { link = "Underlined" },
    ["@markup.raw"] = { ctermfg = green },
    ["@markup.quote"] = { ctermfg = gray },
    ["@markup.list"] = { ctermfg = red },
    ["@diff.plus"] = { link = "Added" },
    ["@diff.minus"] = { link = "Removed" },
    ["@diff.delta"] = { link = "Changed" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.variable"] = { link = "@variable" },

    BufferLineFill = {},
    BufferLineBackground = { ctermfg = gray },
    BufferLineBufferVisible = { ctermfg = gray },
    BufferLineBufferSelected = { ctermfg = yellow, cterm = { bold = true } },
    BufferLineIndicatorSelected = { ctermfg = yellow },
    BufferLineSeparator = { ctermfg = gray },
    BufferLineSeparatorVisible = { ctermfg = gray },
    BufferLineSeparatorSelected = { ctermfg = gray },
    BufferLineCloseButton = { ctermfg = gray },
    BufferLineCloseButtonVisible = { ctermfg = gray },
    BufferLineCloseButtonSelected = { ctermfg = yellow },
    BufferLineModified = { ctermfg = gray },
    BufferLineModifiedVisible = { ctermfg = gray },
    BufferLineModifiedSelected = { ctermfg = yellow },
    BufferLineTab = { ctermfg = gray },
    BufferLineTabSelected = { ctermfg = yellow, cterm = { bold = true } },
    GitSignsAdd = { ctermfg = green },
    GitSignsChange = { ctermfg = yellow },
    GitSignsDelete = { ctermfg = red },
    TelescopeBorder = { ctermfg = gray },
    TelescopeTitle = { ctermfg = yellow },
    TelescopeSelection = { cterm = { reverse = true } },
    TelescopeMatching = { ctermfg = yellow, cterm = { bold = true } },
    TelescopePromptPrefix = { ctermfg = yellow },
    FlashLabel = { ctermfg = magenta, cterm = { reverse = true } },
    FlashMatch = { ctermfg = yellow },
    FlashCurrent = { ctermfg = bright_yellow },
    IblIndent = { ctermfg = gray },
    IblScope = { ctermfg = yellow },
    RainbowDelimiterRed = { ctermfg = red },
    RainbowDelimiterYellow = { ctermfg = yellow },
    RainbowDelimiterBlue = { ctermfg = blue },
    RainbowDelimiterOrange = { ctermfg = bright_red },
    RainbowDelimiterGreen = { ctermfg = green },
    RainbowDelimiterViolet = { ctermfg = magenta },
    RainbowDelimiterCyan = { ctermfg = cyan },
    NeoTreeDirectoryName = { link = "Directory" },
    NeoTreeDirectoryIcon = { link = "Directory" },
    NeoTreeGitAdded = { ctermfg = bright_green },
    NeoTreeGitModified = { ctermfg = yellow },
}

for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
end
